version: "3.7"

services:

  php:
    build:
      context: docker
      dockerfile: Dockerfile-php
    container_name: php
    restart: unless-stopped
    working_dir: /srv
    volumes:
      - .:/srv
      - ./vendor:/srv/vendor:delegated
